### PR TITLE
Install sarge as dependency.

### PR DESCRIPTION
**Pull request by adamghill**

### CODE REVIEW

**Comment by adamcharnock** [comment]
Hi @adamghill. Is sarge needed?

(may be an obvious question - I haven't looked at this project for a while)

**Comment by tilljoel** [comment]
I also needed sarge installed, to avoid

```
ImportError: No module named sarge
```

**Comment by adamghill** [comment]
Yep, sarge is imported for capture_stdout: https://github.com/adamcharnock/dokku-client/blob/7aee95dd9fafbcd9b4d4fc429452dd39a66248de/dokku_client/commands/__init__.py#L3.

**Comment by aduth** [comment]
@adamcharnock, I am receiving the same error message as @tilljoel without sarge installed, and can confirm @adamghill's pull request resolves the error.

**Comment by adamcharnock** [comment]
Done!

**Pull request merged**
